server:
  port: 8090

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      mvc:
        routes:
          - id: USER-SERVICE
            uri: lb://USER-SERVICE
            predicates:
              - Path=/api/v1/**
          - id: MATCH-SERVICE
            uri: lb://MATCH-SERVICE
            predicates:
              - Path=/match/**
          - id: REGISTRATION-SERVICE
            uri: lb://REGISTRATION-SERVICE
            predicates:
              - Path=/api/**


eureka:
  instance:
    prefer-ip-address: true

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka